"""License persistence for QuantSage.

Device code is generated by src/core/device_id.py (persistent UUID).
This module handles license key storage and validation via src/core/license.py.
"""

from __future__ import annotations

import json
from pathlib import Path

# Re-export from the canonical location
from src.core.device_id import get_device_code


def save_license(key: str, device_code: str = "") -> Path:
    """Persist license info to ~/.quantsage/license.json."""
    config_dir = Path.home() / ".quantsage"
    config_dir.mkdir(parents=True, exist_ok=True)
    license_file = config_dir / "license.json"
    data = {
        "key": key,
        "device_code": device_code or get_device_code(),
    }
    license_file.write_text(json.dumps(data, indent=2))
    return license_file


def load_license() -> dict | None:
    """Load persisted license info, or None if absent."""
    license_file = Path.home() / ".quantsage" / "license.json"
    if not license_file.exists():
        return None
    try:
        return json.loads(license_file.read_text())
    except Exception:
        return None


def check_license() -> tuple[bool, str]:
    """Check if the current installation has a valid license."""
    from src.core.license import verify_license

    info = load_license()
    if not info:
        return False, "未找到许可证文件。请在首页输入许可证密钥激活。"

    key = info.get("key", "")
    current_device = get_device_code()

    result = verify_license(key, current_device)
    if not result["valid"]:
        return False, result["reason"]
    return True, f"许可证有效 — 等级: {result['level']}, 到期: {result['exp']}"
