"""Ed25519-signed license verification for QuantSage.

License keys are issued by the Cloudflare Worker (cloud-side signing).
This module ONLY verifies — no signing capability, no private key.

Binary payload format (11 bytes):
  device[0:8] — first 8 bytes of device code (hex decoded)
  exp_days[2]  — uint16 big-endian, days since 2024-01-01 (0xFFFF = permanent)
  level[1]     — 0x00=free, 0x01=pro
+ Ed25519 signature[64] = 75 bytes total

Key format: "QS" + base64url(combined) — ~102 chars, no separators.

MASTER universal keys:
  device_code = "FFFFFFFFFFFFFFFF", level = pro, exp = 0xFFFF (permanent)
  → verify_license skips device matching for MASTER keys.
"""

from __future__ import annotations

import base64
from datetime import date, datetime
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
from cryptography.exceptions import InvalidSignature

# Hardcoded public key (generated by scripts/gen_keypair.py)
# Corresponds to private key stored in Cloudflare Worker env.PRIVATE_KEY_HEX
PUBLIC_KEY_HEX = "3fce9236ba6b25f81e633cea68485906ffced084cb4e4aa0de5dd22554cac9c3"

_EPOCH = date(2024, 1, 1)
_PERMANENT = 0xFFFF
_MASTER_DEVICE = bytes.fromhex("FFFFFFFFFFFFFFFF")  # 8 bytes of 0xFF


def _get_pubkey() -> Ed25519PublicKey:
    return Ed25519PublicKey.from_public_bytes(bytes.fromhex(PUBLIC_KEY_HEX))


def verify_license(key_str: str, device_code: str) -> dict:
    """Verify an Ed25519-signed license key.

    Args:
        key_str: The license key string (starts with "QS")
        device_code: The local device code (hex string, at least 16 chars)

    Returns: {"valid": bool, "level": str, "exp": str, "reason": str}
    """
    try:
        # Strip whitespace only — preserve base64url chars (- and _ are valid!)
        key = key_str.strip().replace(" ", "")
        if key.upper().startswith("QS"):
            key = key[2:]
        # Pad base64url
        pad = 4 - (len(key) % 4)
        if pad < 4:
            key += "=" * pad
        combined = base64.urlsafe_b64decode(key)

        if len(combined) < 75:
            return {"valid": False, "level": "", "exp": "", "reason": "密钥格式无效（长度不足）"}

        payload = combined[:11]
        signature = combined[11:75]

        # Verify Ed25519 signature
        pub = _get_pubkey()
        pub.verify(signature, payload)

        # Parse fields
        dev_bytes = payload[:8]
        exp_days = int.from_bytes(payload[8:10], "big")
        level_byte = payload[10]

        # MASTER universal key: skip device matching
        is_master = (dev_bytes == _MASTER_DEVICE and exp_days == _PERMANENT)

        # Device binding check (skip for MASTER keys)
        if not is_master:
            expected_dev = bytes.fromhex(device_code[:16])
            if dev_bytes != expected_dev:
                return {"valid": False, "level": "", "exp": "", "reason": "密钥与本设备不匹配"}

        # Expiry
        if exp_days == _PERMANENT:
            exp_str = "9999-12-31"
        else:
            from datetime import timedelta
            exp_date = _EPOCH + timedelta(days=exp_days)
            exp_str = exp_date.strftime("%Y-%m-%d")
            if date.today() > exp_date:
                return {"valid": False, "level": "", "exp": exp_str, "reason": f"密钥已过期 ({exp_str})"}

        level = "pro" if level_byte == 1 else "free"
        level_display = "permanent" if exp_days == _PERMANENT else level
        return {"valid": True, "level": level_display, "exp": exp_str, "reason": "验证通过"}

    except InvalidSignature:
        return {"valid": False, "level": "", "exp": "", "reason": "密钥签名无效（伪造或损坏）"}
    except Exception as e:
        return {"valid": False, "level": "", "exp": "", "reason": f"密钥格式无效: {str(e)[:80]}"}
