"""Ed25519-signed license verification for QuantSage.

Replaces the old 16-bit checksum scheme.
Public key is hardcoded — only the developer's private key can generate valid licenses.
"""

from __future__ import annotations

import base64
import json
from datetime import date, datetime
from pathlib import Path
from typing import Optional

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
from cryptography.exceptions import InvalidSignature

# ── Hardcoded public key (generated by scripts/gen_keypair.py) ──
# This is the ONLY public key. The matching private key is held by the developer.
# No private key = no way to forge valid licenses.
PUBLIC_KEY_HEX = "3fce9236ba6b25f81e633cea68485906ffced084cb4e4aa0de5dd22554cac9c3"


def _get_pubkey() -> Ed25519PublicKey:
    return Ed25519PublicKey.from_public_bytes(bytes.fromhex(PUBLIC_KEY_HEX))


# ── Encoding ──

def _encode(payload: dict, signature: bytes) -> str:
    """Encode payload + signature into QS-XXXX-XXXX-... (base64url, compact)."""
    payload_json = json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
    payload_bytes = payload_json.encode("utf-8")
    plen = len(payload_bytes).to_bytes(2, "big")
    combined = plen + payload_bytes + signature
    b64 = base64.urlsafe_b64encode(combined).decode("ascii").rstrip("=")
    groups = [b64[i:i+4] for i in range(0, len(b64), 4)]
    return "QS." + ".".join(groups)  # dot separator — base64url uses - and _


def _decode(key_str: str) -> tuple[dict, bytes]:
    """Decode a license key back into (payload, signature). Supports base64url."""
    key_str = key_str.strip().replace(" ", "")
    if key_str.upper().startswith("QS."):
        key_str = key_str[3:]
    key_str = key_str.replace(".", "")  # dot is our group separator
    # Pad for base64url decoding (multiple of 4)
    pad = 4 - (len(key_str) % 4)
    if pad < 4:
        key_str += "=" * pad
    combined = base64.urlsafe_b64decode(key_str)
    plen = int.from_bytes(combined[:2], "big")
    payload_json = combined[2:2+plen].decode("utf-8")
    signature = combined[2+plen:]
    return json.loads(payload_json), signature


# ── Verification ──

def verify_license(key_str: str, device_code: str) -> dict:
    """Verify an Ed25519-signed license key.

    Args:
        key_str: The license key string (e.g. "QS-XXXX-XXXX-...")
        device_code: Current device fingerprint (first 16 chars compared)

    Returns:
        {"valid": bool, "level": str, "exp": str, "reason": str}
    """
    try:
        payload, signature = _decode(key_str)
        pub = _get_pubkey()
        # Verify Ed25519 signature
        payload_bytes = json.dumps(payload, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
        pub.verify(signature, payload_bytes)

        # Device binding (field "d" = 16-char persistent device code)
        stored_device = payload.get("d", "")
        if stored_device and stored_device != device_code[:16]:
            return {"valid": False, "level": "", "exp": "", "reason": "密钥与本设备不匹配（设备码不同）"}

        # Expiry check
        exp_str = payload.get("exp", "9999-12-31")
        if exp_str != "9999-12-31":
            try:
                exp_date = datetime.strptime(exp_str, "%Y-%m-%d").date()
                if date.today() > exp_date:
                    return {"valid": False, "level": "", "exp": exp_str, "reason": f"密钥已过期 ({exp_str})"}
            except ValueError:
                return {"valid": False, "level": "", "exp": "", "reason": f"无效的过期日期格式: {exp_str}"}

        return {
            "valid": True,
            "level": payload.get("lv", "pro"),
            "exp": exp_str,
            "reason": "验证通过",
        }
    except InvalidSignature:
        return {"valid": False, "level": "", "exp": "", "reason": "密钥签名无效（伪造或损坏）"}
    except Exception as e:
        return {"valid": False, "level": "", "exp": "", "reason": f"密钥格式无效: {str(e)[:80]}"}


# ── Persistence ──

def save_license(key: str, device_code: str) -> Path:
    """Persist license info to ~/.quantsage/license.json."""
    config_dir = Path.home() / ".quantsage"
    config_dir.mkdir(parents=True, exist_ok=True)
    license_file = config_dir / "license.json"
    data = {"key": key, "device_code": device_code}
    license_file.write_text(json.dumps(data, indent=2))
    return license_file


def load_license() -> Optional[dict]:
    """Load persisted license info."""
    license_file = Path.home() / ".quantsage" / "license.json"
    if not license_file.exists():
        return None
    try:
        return json.loads(license_file.read_text())
    except Exception:
        return None


def check_license() -> tuple[bool, str]:
    """Check if the current installation has a valid signed license.

    Returns:
        (is_valid, message)
    """
    from src.deployment.license import get_device_fingerprint
    info = load_license()
    if not info:
        return False, "未找到许可证文件。请通过安装器或配置向导激活。"
    key = info.get("key", "")
    current_device = get_device_fingerprint()

    result = verify_license(key, current_device)
    if not result["valid"]:
        return False, result["reason"]
    return True, f"许可证有效 — 等级: {result['level']}, 到期: {result['exp']}"


# ── Key generation (developer-side, uses private key) ──

def generate_key(device_code: str, level: str = "pro", exp: str = "9999-12-31") -> str:
    """Generate a signed license key.

    Requires quantsage_private.key in the current directory.
    Only the developer should run this.

    Args:
        device_code: Device fingerprint (first 16 chars used)
        level: "free" or "pro"
        exp: Expiry date "YYYY-MM-DD" or "9999-12-31" for permanent

    Returns:
        License key string in QS-XXXX-XXXX-... format
    """
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    import sys as _sys

    # Load private key — search multiple locations
    _key_path = None
    _search_paths = [
        Path("quantsage_private.key"),                          # CWD
        Path(__file__).resolve().parent.parent.parent / "quantsage_private.key",  # project root (from src/core/)
        Path(_sys.executable).parent / "quantsage_private.key",  # next to .exe
    ]
    for _p in _search_paths:
        if _p.exists():
            _key_path = _p
            break

    if _key_path is None:
        raise FileNotFoundError(
            "找不到 quantsage_private.key。\n"
            "请将私钥文件放在以下任一位置：\n"
            f"  - 当前目录: {Path.cwd()}\n"
            f"  - 项目根目录: {Path(__file__).resolve().parent.parent.parent}\n"
            f"  - Keygen.exe 同目录: {Path(_sys.executable).parent}"
        )

    priv_bytes = _key_path.read_bytes()
    priv = Ed25519PrivateKey.from_private_bytes(priv_bytes)

    payload = {
        "d": device_code[:16],  # persistent UUID, 16 hex chars
        "exp": exp,
        "lv": level,
    }
    payload_bytes = json.dumps(payload, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
    signature = priv.sign(payload_bytes)

    return _encode(payload, signature)
